services:
  - type: web
    name: musicdb-bot
    runtime: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    envVars:
      - key: DISCORD_PUBLIC_KEY
        sync: false
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: SYSTEM_STATUS_CHANNEL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: DROPBOX_APP_KEY
        sync: false
      - key: DROPBOX_APP_SECRET
        sync: false
      - key: DROPBOX_REFRESH_TOKEN
        sync: false
      - key: APP_TIMEZONE
        value: "Asia/Tokyo"
